from pathlib import Path
from typing import Protocol


class ICacheManager(Protocol):
    def get_for(self, key: str) -> Path | None: ...
    def set_for(self, key: str) -> None: ...
    def del_key(self, key: str) -> None: ...
